#!/usr/bin/env python3
"""Example 08 · Using the Generated SDK Client.

When you install a Helixor pack, you get a typed SDK generated by
helixor-sdk-gen. This example shows the generated client API.

The generated client provides:
    • Strongly-typed state models (Pydantic)
    • .decide() with typed DecisionResult
    • .decide_batch() for throughput
    • .get_audit_report() for compliance (native runtime ledger)
    • Native C FFI or GraalVM runtime; the generated Python evaluator runs
      only when requested with allow_python_fallback=True
"""

import sys
from pathlib import Path

# The typed client generated from the pack manifest ships inside the runtime wheel.

from regulatorypiiguard import RegulatoryPiiGuardClient, RegulatoryPiiGuardState
from regulatorypiiguard.models import DecisionVerdict


def main() -> None:
    print("=" * 70)
    print(" GENERATED SDK CLIENT — helixor-sdk-gen Output")
    print("=" * 70)

    # Without a native runtime the client refuses to start unless the
    # generated Python evaluator is requested explicitly (set HELIXOR_RUNTIME_LIB
    # to use the native library).
    client = RegulatoryPiiGuardClient(allow_python_fallback=True)

    print(f"\n  Client type:    {type(client).__name__}")
    print(f"  Native engine:  {client.is_native}")
    print(f"  Execution mode: {client.bridge.execution_mode}")

    # ── Typed state construction ──
    print("\n── Typed State Construction ──")

    clean_state = RegulatoryPiiGuardState(
        has_ssn=False,
        has_credit_card=False,
        has_health_record=False,
        has_email=False,
        has_phone=False,
        has_ip=False,
    )

    pii_state = RegulatoryPiiGuardState(
        has_ssn=True,
        has_credit_card=False,
        has_health_record=False,
        has_email=True,
        has_phone=False,
        has_ip=False,
    )

    # ── Decision evaluation ──
    print("\n── Decision Evaluation ──")

    result_clean = client.decide(clean_state)
    print(f"\n  [Clean payload]")
    print(f"    Verdict:     {result_clean.verdict}")
    print(f"    Approved:    {result_clean.is_approved}")
    print(f"    Confidence:  {result_clean.confidence}")
    print(f"    Proof:       {result_clean.proof_sha256[:24]}...")
    print(f"    Latency:     {result_clean.latency_us:.2f} µs")

    result_pii = client.decide(pii_state)
    print(f"\n  [SSN + Email detected]")
    print(f"    Verdict:     {result_pii.verdict}")
    print(f"    Approved:    {result_pii.is_approved}")
    print(f"    Latency:     {result_pii.latency_us:.2f} µs")
    print(f"    Causes:      {[c.factor for c in result_pii.necessary_causes]}")
    if result_pii.counterfactual:
        print(f"    Remedy:      {result_pii.counterfactual.remedy}")
        print(f"    Fix:         {result_pii.counterfactual.target_factor} → {result_pii.counterfactual.required_value}")

    # ── Batch evaluation ──
    print("\n── Batch Evaluation ──")

    batch = [clean_state, pii_state, clean_state, pii_state, clean_state]
    results = client.decide_batch(batch)
    approved = sum(1 for r in results if r.is_approved)
    refused = sum(1 for r in results if not r.is_approved)
    print(f"    Batch size:  {len(batch)}")
    print(f"    Approved:    {approved}")
    print(f"    Refused:     {refused}")

    # ── Audit report ──
    print("\n── Audit Report ──")

    if client.is_native:
        report = client.get_audit_report()
        print(f"    Tier:            {report.tier}")
        print(f"    Total decisions: {report.total_decisions_executed}")
        print(f"    Over quota:      {report.decisions_over_quota}")
        print(f"    Ledger root:     {report.ledger_merkle_root[:16]}...")
    else:
        print("    The audit ledger is kept by the native runtime; the Python")
        print("    evaluator has none, so get_audit_report() raises here.")

    print("\n" + "=" * 70)
    print(" KEY INSIGHT: This client was generated by helixor-sdk-gen from the")
    print(" pack manifest. Every field name, type, and constraint is correct")
    print(" by construction — no hand-written wrappers needed.")
    print("=" * 70)


if __name__ == "__main__":
    main()
